name: magento-compose

services:
  web:
    build: ./web
    expose:
      - "9000"
    environment:
      COMPOSER_AUTH: '{"http-basic": {"repo.magento.com": {"username": "${MAGENTO_REPO_USERNAME}","password": "${MAGENTO_REPO_PASSWORD}"}}}'
    volumes:
      - ./../magento:/var/www/html
    depends_on:
      - db
      - opensearch
      - redis
  db:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
  nginx:
    image: nginx:1.29.1
    volumes:
      - ./../magento:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
  opensearch:
    image: opensearchproject/opensearch:3
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Magento2!.
  redis:
    image: redis:7.2
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
  varnish:
    image: varnish:7.7
    ports:
      - "8080:80"
    volumes:
      - ./varnish/varnish.vcl:/etc/varnish/default.vcl
    depends_on:
      - web